### ISSUE TITLE
cannot import name 'qt_compat'

### ISSUE THREAD

**Issue by laurivosandi** [maqifrnswa/scimpy#19]
Hi, I apt-get installed the packages specified in README on Ubuntu 14.04, cloned the Git repo and performed `sudo python3 setup.py install` but it seems something is still missing?

```
Traceback (most recent call last):
  File "/usr/local/bin/scimpy", line 9, in <module>
    load_entry_point('scimpy==0.0.dev0', 'gui_scripts', 'scimpy')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/scimpy-0.0.dev0-py3.4.egg/scimpy/scimpyui.py", line 9, in <module>
  File "/usr/local/lib/python3.4/dist-packages/scimpy-0.0.dev0-py3.4.egg/scimpy/imptesterui.py", line 9, in <module>
ImportError: cannot import name 'qt_compat'
```

**Comment by maqifrnswa** [comment]
Hi - I'm back working on this - will check it out, and a new release is coming! There was some problems when matplotlib moved from qt4 to qt5 by default, but I've fixed those at least, so this might be fixed as well.

**Comment by maqifrnswa** [comment]
Checked out in 16.10:

```
~/scimpy/installtest/scimpy$` sudo python3 setup.py install
[sudo] password for showard: 
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'windows'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requries'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating scimpy.egg-info
writing dependency_links to scimpy.egg-info/dependency_links.txt
writing top-level names to scimpy.egg-info/top_level.txt
writing scimpy.egg-info/PKG-INFO
writing entry points to scimpy.egg-info/entry_points.txt
writing manifest file 'scimpy.egg-info/SOURCES.txt'
reading manifest file 'scimpy.egg-info/SOURCES.txt'
writing manifest file 'scimpy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/scimpy
copying scimpy/impfitterui.py -> build/lib/scimpy
copying scimpy/speakermodel.py -> build/lib/scimpy
copying scimpy/speakertest.py -> build/lib/scimpy
copying scimpy/speakermodelui.py -> build/lib/scimpy
copying scimpy/scimpyui.py -> build/lib/scimpy
copying scimpy/__init__.py -> build/lib/scimpy
copying scimpy/imptesterui.py -> build/lib/scimpy
copying scimpy/progressmodal.py -> build/lib/scimpy
copying scimpy/centralplotui.py -> build/lib/scimpy
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/impfitterui.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/speakermodel.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/speakertest.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/speakermodelui.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/scimpyui.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/__init__.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/imptesterui.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/progressmodal.py -> build/bdist.linux-x86_64/egg/scimpy
copying build/lib/scimpy/centralplotui.py -> build/bdist.linux-x86_64/egg/scimpy
byte-compiling build/bdist.linux-x86_64/egg/scimpy/impfitterui.py to impfitterui.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/speakermodel.py to speakermodel.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/speakertest.py to speakertest.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/speakermodelui.py to speakermodelui.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/scimpyui.py to scimpyui.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/imptesterui.py to imptesterui.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/progressmodal.py to progressmodal.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/scimpy/centralplotui.py to centralplotui.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying scimpy.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scimpy.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scimpy.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scimpy.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scimpy.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/scimpy-0.0.dev0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing scimpy-0.0.dev0-py3.5.egg
Copying scimpy-0.0.dev0-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding scimpy 0.0.dev0 to easy-install.pth file
Installing scimpy script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/scimpy-0.0.dev0-py3.5.egg
Processing dependencies for scimpy==0.0.dev0
Finished processing dependencies for scimpy==0.0.dev0
```

Do you know if this is still a problem?
