### ISSUE TITLE
Doesn't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by kalle-del-haye** [maqifrnswa/scimpy#28]
I installed Scimpy using apt and your repository.

But it doesn't start and I get this error massage:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 882, in __setitem__
    cval = self.validate[key](val)
KeyError: 'axes.autolimit_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scimpy", line 9, in <module>
    load_entry_point('scimpy==0.0.dev1', 'gui_scripts', 'scimpy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/scimpy/scimpyui.py", line 11, in <module>
    import scimpy.imptesterui as imptesterui
  File "/usr/lib/python3/dist-packages/scimpy/imptesterui.py", line 9, in <module>
    import scimpy.speakertest as speakertest
  File "/usr/lib/python3/dist-packages/scimpy/speakertest.py", line 15, in <module>
    import scimpy.speakermodel as speakermodel
  File "/usr/lib/python3/dist-packages/scimpy/speakermodel.py", line 14, in <module>
    matplotlib.rcParams['axes.autolimit_mode'] = 'round_numbers'
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 888, in __setitem__
    See rcParams.keys() for a list of valid parameters.' % (key,))
KeyError: 'axes.autolimit_mode is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'
```

What can I do?
Do I miss same additional packages?

**Comment by maqifrnswa** [comment]
thanks!

looks like it wants a new feature in matplotlib that is in 17.04 but not 16.04 (all it does it make the plots prettier). I'll put in a check that turns off that feature if it isn't present.

**Comment by kalle-del-haye** [comment]
Your commit fixes the problem and Scimpy is working now.
Thanks for your quick fix.

There is another error message about matplotlib in the terminal:
```
/usr/lib/python3/dist-packages/matplotlib/__init__.py:1352: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
```
It looks like the program is running as expected. So, I'm not sure if this is a critical error.
